# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/
theme = "congo"
baseURL = "https://mkduke424.github.io/myblog/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Congo"

# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
enableRobotsTXT = true

summaryLength = 0

[author]
  name = "Wzrdk3lly"
  image = "img/unicorn.png"
  bio = "I'm just a techie that likes to hack, crypto, skateboarding, and spread positive energy. Join me on this journey as I explore new topics and challenge myself to break into the web3 space. While my main focus will be security/web3, I plan to post general life alpha. Enjoy ;)"
  # links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/mkduke424" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { twitch = "https://twitch.tv/username" },
  { twitter = "https://twitter.com/wzrdk3lly" },
  #   { youtube = "https://youtube.com/username" },
  # ]
